"use strict";
let one = 654;
let two = true;
let three = true;
let four = true;
four = '123';
let five = [1, 2, 3];
five = [21, 22, 23, 24];
let six = [1, 2, 3, 4];
six = ['a', 'b', 'c', 'd'];
let seven = [1, 2, 3, 4];
seven = ['a', 'b', 'c', 'd'];
seven = ['a', 2, 3, 'd'];
let eight = ['hi', 1];
eight = ['bye', 2];
